apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "learn-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "learn-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "learn-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "learn-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
          volumeMounts:
            - mountPath: {{ .Values.persistence.volumeMounts.mountPath }}
              name: {{ .Chart.Name }}-templates
      {{- if .Values.persistence.enabled }}
      volumes:
        - hostPath:
            path: /rancher/{{ .Chart.Name }}/templates
            type: {{ .Values.persistence.volumes.type }}
          name: {{ .Chart.Name }}-templates
      {{ end }}
