apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  name: {{ include "learn-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ include "learn-helm.fullname" . }}.lab.brosy.dev
    http:
      paths:
      - backend:
          service:
            name: {{ include "learn-helm.fullname" . }}
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ include "learn-helm.fullname" . }}.lab.brosy.dev
    secretName: {{ include "learn-helm.fullname" . }}-lab-brosy-dev-crt

