apiVersion: v1
kind: Service
metadata:
  name: learn-helm
  namespace: learn-helm
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  selector:
    app: nginx
  type: ClusterIP