apiVersion: v1
kind: Service
metadata:
  name: {{ include "learn-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  selector:
    {{- include "learn-helm.labels" . | nindent 6 }}
  type: ClusterIP