apiVersion: v1
appVersion: 0.0.1
description: Custom Chart Template
name: custom-template
version: 0.0.1
keywords:
  - template
  - custom
home: https://github.com/dbrosy/rancher-charts/
icon: https://raw.githubusercontent.com/dbrosy/rancher-charts/master/charts/custom-template/template-187x234.png
sources:
  - https://github.com/dbrosy/rancher-charts/charts/custom-template
maintainers:
  - name: dbrosy
    email: dbrosy@hotmail.com
