apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wordpress.fullname" . }}
  labels:
    app: {{ template "wordpress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "wordpress.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "wordpress.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "wordpress.fullname" . }}
          image: {{ .Values.images.wordpress.repository }}:{{ .Values.images.wordpress.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
