apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-helm
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: learn-helm
          image: "nginx:1.19-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
          volumeMounts:
            - mountPath: /etc/nginx/templates
              name: learn-helm-templates
      volumes:
        - hostPath:
            path: /rancher/learn-helm/templates
            type: DirectoryOrCreate
          name: learn-helm-templates
