name: nginx
home: https://github.com/dbrosy/rancher/charts
icon: https://www.nginx.com/wp-content/uploads/2019/10/NGINX-Logo-White-Endorsement-RGB.svg
version: 0.0.2
appVersion: latest
description: 'test nginx container'
keywords:
  - nginx
  - file
  - server
sources:
  - https://github.com/dbrosy/rancher/charts
