apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-helm
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: learn-helm
          image: "nginx:1.19"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:

