apiVersion: v1
kind: Service
metadata:
  name: learn-helm
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  selector:
    workloadID_learn-helm: learn-helm  
  type: ClusterIP